--- #YAML:1.0
name:               Net-NfDump
version:            0.12
abstract:           Perl API for manipulating with nfdump files
author:
    - Tomas Podermanski <tpoder@cis.vutbr.cz>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Socket6:  0.15
    strict:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
