# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-NfDump
version:      0.01_01
version_from: lib/Net/NfDump.pm
installdirs:  site
requires:
    Math::Int64:                   0.09
    Socket6:                       0.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
